### PR TITLE
migrate to @types

### PR DESCRIPTION
**Pull request by mohuk**
- Migration to `@types`
- Remove references to `index.d.ts`, `@types` are picked up by default in Typescript2.0
- Replace `ts-loader` with `awesome-typescript-loader` as it has better compatibility with Typescript2.0 and does not give type errors with `@types`
- Removed `node_modules/.bin` from `npm` scripts as executable gets picked up from the `.bin` folder by default

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi,

Thanks a lot for this. I'll have time to properly review it later in the week, but at a glance it looks great!

**Comment by mohuk** [comment]
I am currently pointing my application to my fork, once you merge this, i will switch it to the original because installing with urls have versioning issues with npm

**Comment by michaelbromley** [comment]
I am curious as to why you need to point to a fork - the @types stuff is just build-time dependencies. If you install from npm in order to consume the module, all you care about is the final `/dist` js files, not the typings stuff. Am I missing something?

**Comment by mohuk** [comment]
true that !

**Pull request merged**
