### PR TITLE
Updated to angular 2.0.0-rc.0.

### PR DESCRIPTION
**Pull request by wolfhoundjesse**
I didn't run your tests. Thanks for this library. It's been helpful!

### CODE REVIEW

**Comment by bobbywarner** [comment]
@wolfhoundjesse I was just going to create a PR for this, then saw you beat me to it!  You should bump to RC1 though.

**Comment by Megalepozy** [comment]
Indeed a needed PR

**Comment by stojankukrika** [comment]
please apply this pull requests, because package didn't work now.

**Comment by sdornan** [comment]
Yes, please merge this.

**Comment by crtranby** [comment]
I would also like to see this PR merged. Currently using this module and really like it's functionality!

**Comment by stojankukrika** [comment]
I change it in local version and everything is working fine. Please merge this to other can work and use this great package,also.

**Comment by michaelbromley** [comment]
Hi everyone. Been a busy week, hence the slow action on my part. But I'm glad this lib is getting some use! 

I've just merged the PR but I am going to just make sure the tests are all working, and clean up any other issues I can before I publish to npm (a little later today).

**Comment by Megalepozy** [comment]
@michaelbromley kewl, thx for the update and the gr8 lib! :)

**Comment by michaelbromley** [comment]
Okay, everyone update to v0.3.0: https://www.npmjs.com/package/ng2-pagination :+1: 

And I forgot to thank @wolfhoundjesse for saving me some time with your PR. Thanks!

**Comment by Megalepozy** [comment]
@michaelbromley thx again! :)

**Pull request merged**
