### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by pawelczak**
Hi @michaelbromley ,

I started using your ng2-pagination and it turned out, that it is really useful for my project. Unfortunately I started to having some issues with pagination, so I needed to investigated what has caused them. It turned out, that problem was on my side :), but while I was running your project I found some issues.

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks for the PR - the changes look good in general. 

I'm wondering what the reason is for the npm `postinstall` script though. What problem does that solve?

**Comment by pawelczak** [comment]
@michaelbromley 
``postinstall`` runs automatically after ``npm install``, so you don't have to remember to run typings installation.

**Comment by michaelbromley** [comment]
But why would a consumer of this package want to install the type defs, which are only used in development of the lib? In fact, the typings.json is not even exported in the npm package. Am I missing something?

**Comment by pawelczak** [comment]
@michaelbromley 
No, it's my mistake. ``postinstall`` is not needed.

**Comment by michaelbromley** [comment]
Ok, thanks for clearing that up. Otherwise, the rest of your fixes are now in version 0.3.1 on NPM :+1:

**Pull request merged**
